# -*- coding: utf-8 -*-
"""Projects.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mNWihgfQH0iFKAPGLQr7wr4qUPjWSLFy

Function imports and image loading
"""

import cv2
import numpy as np

from skimage import io
import matplotlib.pyplot as plt

# Image you are going to use
url = 'https://i.etsystatic.com/7372592/r/il/ee09c5/841312729/il_570xN.841312729_qgg2.jpg'
image = io.imread(url)

img32bit = np.float32(image)

plt.imshow(image.astype(np.uint8))